import jsPDF from "jspdf";
import { UPLOADS_URL } from "../services/api";

// ─── Theme ────────────────────────────────────────────────────────────────────
const C = {
  blue:       [30,  90,  200],
  blueMid:    [59,  130, 246],
  blueLight:  [235, 242, 255],
  green:      [22,  163, 74],
  greenBg:    [240, 253, 244],
  red:        [220, 38,  38],
  redBg:      [254, 242, 242],
  orange:     [234, 88,  12],
  orangeBg:   [255, 247, 237],
  dark:       [30,  30,  30],
  mid:        [100, 116, 139],
  light:      [241, 245, 249],
  line:       [226, 232, 240],
  white:      [255, 255, 255],
};

const M  = 15;          // left/right margin
const CW = 180;         // content width  (210 - 2*15)
const PH = 297;         // A4 height
const FOOTER_H = 18;    // reserved footer space

const isGood = (v) =>
  v && ["Negative", "Low Risk", "Benign", "Normal", "No Tumor"].some((x) => v.includes(x));

// ─── Primitives ───────────────────────────────────────────────────────────────
const sf = (doc, size, style, color) => {
  doc.setFontSize(size);
  doc.setFont("helvetica", style || "normal");
  doc.setTextColor(...(color || C.dark));
};

const rr = (doc, x, y, w, h, r, fill, stroke) => {
  if (fill)   doc.setFillColor(...fill);
  if (stroke) { doc.setDrawColor(...stroke); doc.setLineWidth(0.35); }
  else          doc.setDrawColor(0, 0, 0, 0);
  doc.roundedRect(x, y, w, h, r, r, fill && stroke ? "FD" : fill ? "F" : "D");
};

const bar = (doc, x, y, w, h, pct, fill) => {
  rr(doc, x, y, w, h, h / 2, C.line, null);
  const fw = Math.max((w * Math.min(pct, 100)) / 100, h);
  rr(doc, x, y, fw, h, h / 2, fill, null);
};

// ─── Page helpers ─────────────────────────────────────────────────────────────
function drawPageBorderAndFooter(doc, dateStr) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  // Border
  doc.setDrawColor(...C.line);
  doc.setLineWidth(0.5);
  doc.rect(5, 5, pw - 10, ph - 10);
  // Footer line
  doc.setDrawColor(...C.line);
  doc.setLineWidth(0.3);
  doc.line(M, ph - FOOTER_H, M + CW, ph - FOOTER_H);
  sf(doc, 7.5, "normal", C.mid);
  doc.text(
    `Generated by MedAI Healthcare  |  ${dateStr}`,
    pw / 2, ph - FOOTER_H + 7,
    { align: "center" }
  );
}

// ─── Section helpers ──────────────────────────────────────────────────────────
function secHeader(doc, title, y) {
  doc.setFillColor(...C.blue);
  doc.rect(M, y, 3, 6, "F");
  sf(doc, 9, "bold", C.blue);
  doc.text(title.toUpperCase(), M + 6, y + 5);
  return y + 12;
}

function divLine(doc, y) {
  doc.setDrawColor(...C.line);
  doc.setLineWidth(0.3);
  doc.line(M, y, M + CW, y);
  return y + 8;
}

// Ensure there's enough room; if not, add a new page and reset y
function ensureSpace(doc, y, needed, dateStr) {
  if (y + needed > PH - FOOTER_H - 5) {
    drawPageBorderAndFooter(doc, dateStr);
    doc.addPage();
    return 20;
  }
  return y;
}

// ─── Image loader ─────────────────────────────────────────────────────────────
function loadImg(url) {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      try {
        const c = document.createElement("canvas");
        c.width  = img.naturalWidth;
        c.height = img.naturalHeight;
        c.getContext("2d").drawImage(img, 0, 0);
        resolve(c.toDataURL("image/jpeg", 0.85));
      } catch { resolve(null); }
    };
    img.onerror = () => resolve(null);
    img.src = url;
  });
}

// ─── Main ─────────────────────────────────────────────────────────────────────
export async function generateReportPDF(report) {
  // Load scan image before building PDF
  let scanB64 = null;
  if (report.image_path) {
    const url = report.image_path.startsWith("http")
      ? report.image_path
      : `${UPLOADS_URL}/${report.image_path}`;
    scanB64 = await loadImg(url);
  }

  const doc  = new jsPDF({ unit: "mm", format: "a4" });
  const PW   = doc.internal.pageSize.getWidth();
  const dateStr = new Date().toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" });
  let y = 0;

  // ── HEADER ──────────────────────────────────────────────────────────────────
  doc.setFillColor(...C.blue);
  doc.rect(0, 0, PW, 36, "F");
  doc.setFillColor(20, 70, 180);
  doc.rect(0, 27, PW, 9, "F");

  // Decorative rings
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(0.25);
  doc.circle(PW - 20, 11, 13, "D");
  doc.circle(PW - 20, 11, 8,  "D");

  sf(doc, 17, "bold", C.white);
  doc.text("MedAI Healthcare", PW / 2, 15, { align: "center" });
  sf(doc, 8.5, "normal", [200, 220, 255]);
  doc.text("AI-Powered Disease Detection Report", PW / 2, 23, { align: "center" });

  // Gold accent strip
  doc.setFillColor(255, 196, 0);
  doc.rect(0, 35.5, PW, 1.2, "F");

  y = 44;

  // ── REPORT META ─────────────────────────────────────────────────────────────
  rr(doc, M, y, CW, 22, 3, C.light, C.line);

  // Report ID
  sf(doc, 7, "normal", C.mid);
  doc.text("REPORT ID", M + 5, y + 7);
  sf(doc, 9, "bold", C.dark);
  doc.text(`#${(report.id || "").slice(0, 8).toUpperCase()}`, M + 5, y + 14);

  // Date
  const repDate = report.created_at
    ? new Date(report.created_at).toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" })
    : "N/A";
  sf(doc, 7, "normal", C.mid);
  doc.text("DATE", PW / 2, y + 7, { align: "center" });
  sf(doc, 9, "bold", C.dark);
  doc.text(repDate, PW / 2, y + 14, { align: "center" });

  // Status badge
  const isReviewed  = report.status === "Reviewed";
  const badgeFill   = isReviewed ? C.greenBg  : C.orangeBg;
  const badgeColor  = isReviewed ? C.green    : C.orange;
  const statusLabel = report.status || "Pending Review";
  const badgeW      = Math.min(statusLabel.length * 2.2 + 8, 44);
  rr(doc, M + CW - badgeW - 4, y + 5, badgeW, 12, 3, badgeFill, null);
  sf(doc, 7.5, "bold", badgeColor);
  doc.text(statusLabel, M + CW - badgeW / 2 - 4, y + 13, { align: "center" });

  y += 30;

  // ── PATIENT INFORMATION ──────────────────────────────────────────────────────
  y = secHeader(doc, "Patient Information", y);
  rr(doc, M, y, CW, 28, 3, C.white, C.line);

  const c1 = M + 5;
  const c2 = M + CW / 2 + 5;

  const lv = (label, value, x, ry) => {
    sf(doc, 8, "normal", C.mid);
    doc.text(label, x, ry);
    sf(doc, 8.5, "bold", C.dark);
    doc.text(String(value || "N/A"), x + 28, ry);
  };

  lv("Full Name",   report.patient_name   || "N/A",                          c1, y + 9);
  lv("Age",         report.patient_age    ? `${report.patient_age} yrs` : "N/A", c2, y + 9);
  lv("Gender",      report.patient_gender || "N/A",                          c1, y + 19);
  lv("Blood Group", report.patient_blood_group || "N/A",                     c2, y + 19);

  // Center vertical divider
  doc.setDrawColor(...C.line);
  doc.setLineWidth(0.25);
  doc.line(M + CW / 2, y + 3, M + CW / 2, y + 25);

  y += 36;

  // ── TEST RESULT ──────────────────────────────────────────────────────────────
  y = secHeader(doc, "Test Result", y);

  const good      = isGood(report.result);
  const resFill   = good ? C.greenBg : C.redBg;
  const resClr    = good ? C.green   : C.red;
  const resBorder = good ? [134, 239, 172] : [252, 165, 165];

  const hasConf = report.confidence != null;
  const cardH   = hasConf ? 46 : 38;
  rr(doc, M, y, CW, cardH, 3, resFill, resBorder);

  // Disease pill
  rr(doc, M + 5, y + 5, 62, 8, 2, good ? [220, 252, 231] : [254, 226, 226], null);
  sf(doc, 7.5, "bold", resClr);
  doc.text(report.report_type || "N/A", M + 36, y + 10.5, { align: "center" });

  // Result
  sf(doc, 14, "bold", resClr);
  doc.text(report.result || "N/A", M + 5, y + 24);

  // Verdict
  sf(doc, 7.5, "normal", C.mid);
  doc.text(
    good ? "No abnormality detected" : "Abnormality detected — consult doctor",
    M + 5, y + 31
  );

  // Confidence bar
  if (hasConf) {
    const bx = M + 5;
    const by = y + 38;
    const bw = CW - 28;
    sf(doc, 7.5, "normal", C.mid);
    doc.text("Confidence", bx, by);
    bar(doc, bx + 26, by - 3.5, bw - 26, 4, report.confidence, C.blueMid);
    sf(doc, 8, "bold", C.dark);
    doc.text(`${report.confidence}%`, bx + bw + 2, by);
  }

  y += cardH + 6;

  // Risk score
  if (report.risk_score != null) {
    rr(doc, M, y, CW, 13, 3, C.light, C.line);
    const rClr = report.risk_score > 60 ? C.red : report.risk_score > 30 ? C.orange : C.green;
    sf(doc, 8, "normal", C.mid);
    doc.text("Risk Score", M + 5, y + 8.5);
    bar(doc, M + 30, y + 4.5, CW - 50, 4, report.risk_score, rClr);
    sf(doc, 8, "bold", rClr);
    doc.text(`${report.risk_score}/100`, M + CW - 18, y + 8.5);
    y += 20;
  }

  // ── SCAN IMAGE ───────────────────────────────────────────────────────────────
  y = divLine(doc, y);
  y = ensureSpace(doc, y, 75, dateStr);
  y = secHeader(doc, "Medical Scan Image", y);

  if (scanB64) {
    // Compute aspect-correct height (max 60mm)
    const imgH = 58;
    rr(doc, M, y, CW, imgH + 4, 3, C.white, C.line);
    doc.addImage(scanB64, "JPEG", M + 2, y + 2, CW - 4, imgH, "", "FAST");
    y += imgH + 10;
  } else {
    rr(doc, M, y, CW, 13, 3, C.light, C.line);
    sf(doc, 8, "italic", C.mid);
    doc.text("No scan image uploaded for this report.", PW / 2, y + 8.5, { align: "center" });
    y += 20;
  }

  // ── AI RECOMMENDATION ────────────────────────────────────────────────────────
  if (report.recommendation) {
    y = divLine(doc, y);
    const recLines = doc.splitTextToSize(report.recommendation, CW - 14);
    const recH     = recLines.length * 5 + 10;
    y = ensureSpace(doc, y, recH + 20, dateStr);
    y = secHeader(doc, "AI Recommendation", y);
    rr(doc, M, y, CW, recH, 3, C.blueLight, [147, 197, 253]);
    doc.setFillColor(...C.blueMid);
    doc.roundedRect(M, y, 3, recH, 1.5, 1.5, "F");
    sf(doc, 8.5, "normal", [30, 64, 175]);
    doc.text(recLines, M + 8, y + 7);
    y += recH + 8;
  }

  // ── DOCTOR'S NOTES ───────────────────────────────────────────────────────────
  if (report.doctor_notes) {
    y = divLine(doc, y);
    const noteLines = doc.splitTextToSize(report.doctor_notes, CW - 14);
    const noteH     = noteLines.length * 5 + 10;
    y = ensureSpace(doc, y, noteH + 20, dateStr);
    y = secHeader(doc, "Doctor's Notes", y);
    rr(doc, M, y, CW, noteH, 3, [250, 245, 255], [196, 181, 253]);
    doc.setFillColor(124, 58, 237);
    doc.roundedRect(M, y, 3, noteH, 1.5, 1.5, "F");
    sf(doc, 8.5, "normal", [76, 29, 149]);
    doc.text(noteLines, M + 8, y + 7);
    y += noteH + 8;
  }

  // ── DOCTOR SIGNATURE ─────────────────────────────────────────────────────────
  if (report.doctor_name || report.hospital) {
    y = divLine(doc, y);
    y = ensureSpace(doc, y, 30, dateStr);
    rr(doc, M, y, CW, 22, 3, C.light, C.line);
    sf(doc, 7.5, "normal", C.mid);
    doc.text("Reviewed & Authorized by", M + 5, y + 7);
    sf(doc, 9, "bold", C.dark);
    doc.text(report.doctor_name ? `Dr. ${report.doctor_name}` : "Authorized Physician", M + 5, y + 14);
    if (report.specialization || report.hospital) {
      sf(doc, 7.5, "normal", C.mid);
      doc.text([report.specialization, report.hospital].filter(Boolean).join("  |  "), M + 5, y + 20);
    }
    // Signature line
    doc.setDrawColor(...C.mid);
    doc.setLineWidth(0.4);
    doc.line(M + CW - 52, y + 18, M + CW - 5, y + 18);
    sf(doc, 7, "italic", C.mid);
    doc.text("Signature", M + CW - 29, y + 22, { align: "center" });
    y += 30;
  }

  // ── DISCLAIMER ───────────────────────────────────────────────────────────────
  y = divLine(doc, y);
  const disc = "DISCLAIMER: This report is generated by an AI-assisted diagnostic system for informational purposes only. It does not constitute a medical diagnosis. Please consult a qualified healthcare professional for clinical advice.";
  const discLines = doc.splitTextToSize(disc, CW - 12);
  const discH     = discLines.length * 4.8 + 9;
  y = ensureSpace(doc, y, discH + 10, dateStr);
  rr(doc, M, y, CW, discH, 3, [255, 251, 235], [253, 230, 138]);
  sf(doc, 7.5, "normal", [133, 100, 4]);
  doc.text(discLines, M + 6, y + 7);
  y += discH + 4;

  // ── FOOTER + BORDER on every page ────────────────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawPageBorderAndFooter(doc, dateStr);
  }

  doc.save(`MedAI_Report_${(report.id || "").slice(0, 8) || "download"}.pdf`);
}
